SET IDENTITY_INSERT [dbo].[tb_Country] ON
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (62, N'The Gambia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (63, N'Georgia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (64, N'Germany')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (65, N'Ghana')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (66, N'Greece')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (67, N'Grenada')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (68, N'Guatemala')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (69, N'Guinea')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (70, N'Guinea-Bissau')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (71, N'Guyana')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (72, N'Haiti')


INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (73, N'Honduras')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (74, N'Hungary')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (75, N'Iceland')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (76, N'India')

INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (77, N'Indonesia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (78, N'Iran')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (79, N'Iraq')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (80, N'Ireland')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (81, N'Israel')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (82, N'Italy')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (83, N'Jamaica')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (84, N'Japan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (85, N'Jordan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (86, N'Kazakhstan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (87, N'Kenya')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (88, N'Kazakhstan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (89, N'Kiribati')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (90, N'North Korea')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (91, N'South Korea')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (92, N'Kosovo')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (93, N'Kuwait')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (94, N'Kyrgyzstan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (95, N'Laos')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (96, N'Latvia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (97, N'Lebanon')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (98, N'Lesotho')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (99, N'Liberia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (100, N'Libya')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (101, N'Liechtenstein')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (102, N'Lithuania')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (103, N'Luxembourg')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (104, N'Macedonia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (105, N'Madagascar')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (106, N'Malawi')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (107, N'Malaysia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (108, N'Maldives')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (109, N'Mali')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (110, N'Malta')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (111, N'Marshall Islands')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (112, N'Mauritania')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (113, N'Mauritius')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (114, N'Mexico')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (115, N'Mexico')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (116, N'Federated States of Micronesia')

INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (117, N'Moldova')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (118, N'Monaco')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (119, N'Mongolia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (120, N'Montenegro')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (121, N'Morocco')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (122, N'Mozambique')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (123, N'Myanmar (Burma)')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (124, N'Namibia')


INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (125, N'Nauru')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (126, N'Nepal')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (127, N'Netherlands')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (128, N'New Zealand')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (129, N'Nicaragua')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (130, N'Niger')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (131, N'Nigeria')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (132, N'Norway')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (133, N'Oman')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (134, N'Pakistan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (135, N'Palau')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (136, N'Panama')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (137, N'Papua New Guinea')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (138, N'Paraguay')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (139, N'Peru')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (140, N'Philippines')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (141, N'Poland')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (142, N'Portugal')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (143, N'Qatar')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (144, N'Romania')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (145, N'Russia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (146, N'Rwanda')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (147, N'Saint Kitts and Nevis')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (148, N'Saint Lucia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (149, N'Saint Vincent and the Grenadines')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (150, N'Samoa')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (151, N'San Marino')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (152, N'Sao Tome and Principe')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (153, N'Saudi Arabia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (154, N'Senegal')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (155, N'Serbia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (156, N'Seychelles')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (157, N'Sierra Leone')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (158, N'Singapore')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (159, N'Slovakia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (160, N'Slovenia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (161, N'Solomon Islands')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (162, N'Somalia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (163, N'South Africa')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (164, N'South Sudan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (165, N'Spain')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (166, N'Sri Lanka')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (167, N'Sudan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (168, N'Suriname')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (169, N'Swaziland')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (170, N'Sweden')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (171, N'Switzerland')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (172, N'Syria')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (173, N'Taiwan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (174, N'Tajikistan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (175, N'Tanzania')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (176, N'Thailand')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (177, N'Togo')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (178, N'Tonga')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (179, N'Trinidad and Tobago')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (180, N'Tunisia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (181, N'Turkey')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (182, N'Turkmenistan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (183, N'Tuvalu')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (184, N'Uganda')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (185, N'Ukraine')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (186, N'United Arab Emirates')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (187, N'United Kingdom')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (188, N'United States of America')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (189, N'Uruguay')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (190, N'Uzbekistan')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (191, N'Vanuatu')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (192, N'Vatican City')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (193, N'Venezuela')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (194, N'Vietnam')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (195, N'Yemen')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (196, N'Zambia')
INSERT INTO [dbo].[tb_Country] ([countryId],[Country]) VALUES (197, N'Zimbabwe')

SET IDENTITY_INSERT [dbo].[tb_Country] OFF
