//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TELDAMIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Country
    {
        public int countryId { get; set; }
        public string Country { get; set; }
        public string Capital { get; set; }
    }
}
