using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TELDALUXURY.Models
{
    public class CreateUserLogin
    {
        [Required(ErrorMessage = "This field is required")]
        [StringLength(50), MinLength(3), MaxLength(50)]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [StringLength(50), MinLength(3), MaxLength(50)]
        public string LastName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [StringLength(50), MinLength(3), MaxLength(50)]
        public string OtherName { get; set; }
        //public string StatusId { get; set; }  // autogenerated from stored procedure
        //public string DateAdded { get; set; }   // autogenerated from stored procedure 

        [Required(ErrorMessage = "You have to enter your phone number to continue")]
        [StringLength(50), MinLength(3), MaxLength(50)]
        public string PhoneNumber { get; set; }
        //public string UserName { get; set; }

        [Required(ErrorMessage = "You need an email address to create an account"), DataType(DataType.EmailAddress)]
        [StringLength(50), MinLength(3), MaxLength(50)]
        public string EmailAddress { get; set; }

        [Required(ErrorMessage = "This field is required"), DataType(DataType.Password)]
        [StringLength(50), MinLength(3), MaxLength(50)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Confirm password doesn't match, Type again !")]
        public string ConfirmPassword { get; set; }
    }
}
