//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPPER_WEBAPI_TELDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ErrorLog
    {
        public int logId { get; set; }
        public string Error { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> DateandTime { get; set; }
    }
}
