//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Sales
    {
        public int SalesId { get; set; }
        public string Item { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
