//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPPER_WEBAPI_TELDA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class theldaluxuryEntities : DbContext
    {
        public theldaluxuryEntities()
            : base("name=theldaluxuryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_AddNewItem> tb_AddNewItem { get; set; }
        public virtual DbSet<tb_AdminRole> tb_AdminRole { get; set; }
        public virtual DbSet<tb_AdminUser> tb_AdminUser { get; set; }
        public virtual DbSet<tb_Country> tb_Country { get; set; }
        public virtual DbSet<tb_ErrorLog> tb_ErrorLog { get; set; }
        public virtual DbSet<tb_Item> tb_Item { get; set; }
        public virtual DbSet<tb_ItemCategory> tb_ItemCategory { get; set; }
        public virtual DbSet<tb_ItemStatus> tb_ItemStatus { get; set; }
        public virtual DbSet<tb_LGA> tb_LGA { get; set; }
        public virtual DbSet<tb_Sales> tb_Sales { get; set; }
        public virtual DbSet<tb_State> tb_State { get; set; }
        public virtual DbSet<tb_Users> tb_Users { get; set; }
        public virtual DbSet<ViewCountry> ViewCountries { get; set; }
    }
}
