<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Index.aspx.cs" Inherits="TELDALUXURY_WEBSITE.Admin.Index" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>TELDALUXURY - ADMIN</title>
    <style type="text/css">
        #form1 {
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <h2>TEST TABLE FOR ASP.NET WEB FORMS</h2>

        <%--<asp:Table ID="Table1" runat="server" BorderStyle="Solid" Height="74px" Width="145px" BorderColor="#999966" BorderWidth="0.1em">
            <asp:TableHeaderRow>
                <asp:TableCell></asp:TableCell>
            </asp:TableHeaderRow>
        </asp:Table>--%>
        <%--<asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BorderColor="#999966" BorderStyle="Solid" BorderWidth="0.1em" DataKeyNames="Id" DataSourceID="SqlDataSource1" Font-Size="11px" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" ShowFooter="True">
            <AlternatingRowStyle BackColor="#FFD5D5" BorderColor="#666666" Font-Names="Consolas" Font-Size="Smaller" />
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                <asp:BoundField DataField="PasswordHash" HeaderText="PasswordHash" SortExpression="PasswordHash" />
                <asp:CheckBoxField DataField="isUpdated" HeaderText="isUpdated" SortExpression="isUpdated" />
                <asp:CheckBoxField DataField="PasswordChanged" HeaderText="PasswordChanged" SortExpression="PasswordChanged" />
                <asp:CheckBoxField DataField="isDeleted" HeaderText="isDeleted" SortExpression="isDeleted" />
            </Columns>
            <EmptyDataRowStyle BackColor="White" BorderColor="White" BorderStyle="Solid" />
            <HeaderStyle BackColor="#FFBFBF" BorderStyle="Solid" />

        </asp:GridView>--%>
        <%--<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Dapper_DemoConnectionString %>" OnSelecting="SqlDataSource1_Selecting" SelectCommand="SELECT * FROM [StaffLogin]"></asp:SqlDataSource>--%>
        <asp:DropDownList ID="DropDownList1" runat="server" Height="16px" Width="219px">
        </asp:DropDownList>
    </form>
</body>
</html>
